### PR TITLE
CASMPET-5897 add function to verify upgrade

### PR DESCRIPTION
**Pull request by leliasen-hpe**
### Summary and Scope

- Adds ability to get report as a dictionary, add function to verify upgrade. 
- Implements CASMPET-5892 by adding function to check current version.
- Relates to: CASMINST-5116 which is automating stage 4 of the upgrade

#### Issue Type

- RFE Pull Request

### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (if yes, please include results or a description of the test)
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)
 
### Idempotency
 

This change implements read only functions to help verify the upgrade was successful. The functions have been tested on their own.

### CODE REVIEW

**Review by bklei — APPROVED** [review]

**Review by cdelatte-hpe — APPROVED** [review]

**Review by heemstra — APPROVED** [review]

**Comment by rustydb** [comment]
Holding this for now. There's a reorg coming to make builds faster, that'll merge into main first unless it's delayed past Monday.

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
Rebased/rebuilding, will merge pending successful build.

**Review by heemstra — APPROVED** [review]

**Comment by rustydb** [comment]
Triggered a rebuild.

**Comment by rustydb** [comment]
Fast-forward Succeeded!

**Pull request merged**
