### PR TITLE
Removed standalone provisioner for installed.repos

### PR DESCRIPTION
**Pull request by jpdavis-prof**
### Summary and Scope

- Fixes: installed.repos wasn't being published for storage-ceph

#### Issue Type

- Bugfix

### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (if yes, please include results or a description of the test)
- [x] I tested this on a vshasta system (if yes, please include results or a description of the test)
- [x] I tested this on a vagrant environment (if yes, please include results or a description of the test)
  
### Risks and Mitigations
 
None

### CODE REVIEW

**Review by rustydb — COMMENTED** [review]
On phone.. but this only in this pkr file and not the others in ncn-node-images?

**Comment by jpdavis-prof** [comment]
> On phone.. but this only in this pkr file and not the others in ncn-node-images?

It's already good in the pkr files. I think it was just overlooked for storage-ceph.

**Comment by rustydb** [comment]
Fast-forward Succeeded!

**Pull request merged**
