### PR TITLE
VSHA-436 - Fix var to the livecd tests trigger

### PR DESCRIPTION
**Pull request by wiltonpaulo**
### Summary and Scope

- Fixes: [PR-493](https://github.com/Cray-HPE/node-images/pull/493)
- Relates to:  Relates to: VSHA-436, VSHA-424, VSHA-442

After merging the PR-493, the stage to trigger livecd tests is sending a "null" value as an argument.
This PR must fix this issue.  

#### Issue Type

- Bugfix Pull Request

### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (if yes, please include results or a description of the test)
- [x] I tested this on a vshasta system (if yes, please include results or a description of the test)
- [x] I tested this on a vagrant environment (if yes, please include results or a description of the test)

### CODE REVIEW

**Review by rustydb — APPROVED** [review]
Could use lowercase in this instance but otherwise it looks good.

**Comment by wiltonpaulo** [comment]
> Could use lowercase in this instance but otherwise it looks good.

changed to commitVersion

**Comment by rustydb** [comment]
Fast-forward Succeeded!

**Pull request merged**
